import Fade from 'react-reveal';

export default function About() {
    return (
        <div className="About">
            <div className="AboutHeader">
                <div className="AboutContainer">
                    <h1 className="AboutHeaderLabel">
                        Making each stop <u className="underlign-design">count.</u>
                    </h1>
                    <p className="AboutHeaderText">
                        This is the official website of <span className="waypoint">Waypoint</span>, a part of the Arangkadata project by the University of the Philippines – Diliman, funded by the Department of Science and Technology, and supported by the Department of Transportation.
                    </p>
                </div>
            </div>
            <div style={{backgroundColor: '#F8F9FD', width: '100%', height: '6rem'}}/>
            <div className="AboutWriteUp">
                <Fade><h1 className="WriteUpHeader">The Website</h1></Fade>
                <Fade><div className="WriteUpText">
                    In this website, we will be providing data regarding passenger traffic. This data includes where the stops are, how many people in average are seen at each stop, and how many of them alight and board at these stops. The data being provided is generated by a combination of a <a href="https://github.com/alexattia/ExtendedTinyFaces" target="_blank" rel="noreferrer" className="wrap-text"><span className="custom-underline">Computer-Vision algorithm</span></a> and our own semi-automated annotation system. This annotation system utilizes the <a href="https://arangkadata.com/about/" rel="noreferrer" target="_blank" className="wrap-text"><span className="custom-underline">required onboard electronic devices</span></a>  in modern public-utility-vehicles (PUVs) to help human annotators in trimming down the amount of footage needed to be reviewed to generate the data that the site provides. Waypoint’s aim is to help all in the transportation sector as well as those who utilize their services in improving the current transportation environment in the country.
                </div></Fade>
            </div>
        </div>
    )
}